New-Item -ItemType Directory -Force -Path .github\workflows | Out-Null

@"
name: Build macOS App

on:
  workflow_dispatch: {}      # กดรันเองได้
  push:
    branches: [ main ]       # หรือจะลบส่วนนี้ถ้าไม่อยาก build ทุก push

jobs:
  build:
    runs-on: macos-latest    # macOS ARM64 (M1/M2/M3)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install "fastapi>=0.110" "uvicorn[standard]>=0.30" "iqoptionapi>=0.1.6" \
                        "numpy>=1.24" "pandas>=2.0" "pandas-ta>=0.3.14b0" "scikit-learn>=1.3" \
                        "joblib>=1.3" "python-machineid>=0.9.6" "PyNaCl>=1.5" \
                        "websocket-client>=1.6" "pydantic>=2.0" pyinstaller
          fi

      - name: Build .app with PyInstaller (windowed + icon)
        run: |
          pyinstaller --noconfirm --clean \
            --windowed \
            --name bot_app \
            --icon app.icns \
            --hidden-import pandas_ta --hidden-import sklearn --hidden-import iqoptionapi \
            --add-data "index.html:." \
            --add-data "market_hours.json:." \
            --add-data "actives.json:." \
            --add-data "ai_meta.json:." \
            --add-data "models:models" \
            --add-data "strategies:strategies" \
            --add-data "services:services" \
            --add-data "database:database" \
            main.py

      - name: Upload artifact (.app)
        uses: actions/upload-artifact@v4
        with:
          name: bot_app_macos
          path: dist/bot_app.app
"@ | Set-Content .github\workflows\build-macos.yml -Encoding UTF8

git add .github\workflows\build-macos.yml
git commit -m "chore(ci): add macOS build workflow"
git push
